[package]
name = "helloworld-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
libloading = "0.8.8"

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.36"

[profile.dev.build-override]
debug = true
